homepage:
    path: /
    controller: App\Controller\DefaultController::index

# une nouvelle route avec une variable de chemin cette fois !
hello:
    path: /hello/{name}
    controller: App\Controller\DefaultController::hello
    defaults:
        name: à toi
    requirements:
        name: '[^/]+'